export const navData = [
    { label: 'HOME', href: '/' },
    {
        label: 'DEEP CLEANING',
        href: '#',
        submenu: [
            { label: 'Apartment Deep Cleaning', href: '/apartment-deep-cleaning' },
            { label: 'Villa Deep Cleaning', href: '/villa-deep-cleaning' },
            { label: 'Office Deep Cleaning', href: '/office-deep-cleaning' },
            { label: 'Floor Deep Cleaning Services', href: '/floor-deep-cleaning-services' },
            { label: 'Move In Move Out Cleaning', href: '/move-in-move-out-cleaning' },
            { label: 'AC Duct Cleaning', href: '/ac-duct-cleaning' },
            { label: 'Villa Facade Cleaning Services', href: '/villa-facade-cleaning-services' },
            { label: 'Outside Deep Cleaning', href: '/outside-deep-cleaning' },
            { label: 'Outside Power Wash', href: '/outside-power-wash' },
            { label: 'Rooftop Cleaning Services', href: '/rooftop-cleaning-services' },
            { label: 'Outside Window Cleaning', href: '/outside-window-cleaning' },
            { label: 'Post Construction Cleaning in Dubai', href: '/post-construction-cleaning-in-dubai' },
            { label: 'Bathroom Deep Cleaning', href: '/bathroom-deep-cleaning' },
            { label: 'Steam Deep Cleaning', href: '/steam-deep-cleaning' },
            { label: 'Deep Cleaning Of Restaurant', href: '/deep-cleaning-of-restaurant' },
            { label: 'Deep Cleaning Of Warehouse', href: '/deep-cleaning-of-warehouse' },
            { label: 'Deep Cleaning Of Shops', href: '/deep-cleaning-of-shops' },
            { label: 'Kitchen Deep Cleaning', href: '/kitchen-deep-cleaning' },
            { label: 'Balcony Deep Cleaning', href: '/balcony-deep-cleaning' },
        ],
    },
    {
        label: 'CLEANING SERVICES',
        href: '#',
        submenu: [
            { label: 'Mattress Cleaning Services', href: '/mattress-cleaning-services' },
            { label: 'Curtain UV & Steam Machine', href: '/Curtain-uv-and-steam-machine' },
            { label: 'Sofa Shampooing', href: '/sofa-shampooing' },
			{ label: 'Carpet Shampooing', href: '/carpet-shampooing' },
            { label: 'Water Tank Cleaning Services', href: '/water-tank-cleaning-services' },
            { label: 'Swimming Pool Cleaning', href: '/swimming-pool-cleaning' },
            { label: 'Artificial Grass Cleaning', href: '/artificial-grass-cleaning' },
            { label: 'Marble Polishing Services', href: '/marble-polishing-services' },
        ],
    },
    {
        label: 'PAINTING SERVICES',
        href: '#',
        submenu: [
            { label: 'Office Painting Services', href: '/office-painting-services' },
            { label: 'Villa Painting Services', href: '/villa-painting-services' },
            { label: 'Apartment Painting', href: '/apartment-painting' },
        ],
    },
    { label: 'ABOUT US', href: '/about-us' },
    { label: 'CONTACT US', href: '/contact-us' },
];